spring:
  application:
    name: nacos-consul-adapter
  cloud:
    nacos:
      discovery:
        server-addr: ynyt-nacos.default:8848
        namespace: 2edd9fd3-4e14-4015-af7d-e9c19c7fb3c6
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}